### ISSUE TITLE
security: add branch protections to prevent accidental pushes to `main`

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/pacta.data.preparation#14]
This shouldn't be possible for anyone (even admins).

_Originally posted by @cjyetman in https://github.com/RMI-PACTA/pacta.data.preparation/issues/309#issuecomment-1997177376_

**Comment by cjyetman** [comment]
this repo currently has:
<img width="903" alt="Screenshot 2024-04-29 at 11 49 49" src="https://github.com/RMI-PACTA/pacta.data.preparation/assets/1708872/568fa453-fca8-4df6-b196-34941fbe0095">
<img width="918" alt="Screenshot 2024-04-29 at 11 49 56" src="https://github.com/RMI-PACTA/pacta.data.preparation/assets/1708872/8ad984b5-2cec-4335-9d6f-1aa84b2b8a8a">

**Comment by jdhoffa** [comment]
Confirming that this works (even for admins)
<img width="906" alt="Screenshot 2024-04-29 at 11 57 04" src="https://github.com/RMI-PACTA/pacta.data.preparation/assets/8741309/b036f387-b00d-4798-998d-e8f33d5f6cc9">
